spring:
  application:
    name: yj-sample-webapp
  profiles:
    active: local
  mvc:
    locale: ko_KR
  messages:
    basename: classpath:/messages/message
    encoding: UTF-8
config:
  restTemplate:
    timeout: 10000
    maxConnTotal: 200
    maxConnPerRoute: 100
---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: parking
azure:
  application-insights:
    instrumentation-key: 6c7d751a-d1a4-48ce-8b62-547d6e6c0ed4
server:
  port: 8000
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: parking
azure:
  application-insights:
    instrumentation-key: 6c7d751a-d1a4-48ce-8b62-547d6e6c0ed4
server:
  port: 8000
